pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  stage('execute ansible code') {
    steps {
        dir("../../prechecks-demo") {
            sh 'ansible-playbook prechecks.yml'
        }
     }
   }
  }  
}
