---
- name: Pre checks
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Creates directory
      file:
        path: ../Reports
        state: directory
        mode: 0775
